[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "structio"
version = "1.0.0"
description = "A small Python library based on the BytesIO object from the standard library, designed to make parsing and editing binary files easier."
readme = "README.md"
requires-python = ">=3.2"

[project.urls]
"Homepage" = "https://github.com/lingeringwillx/StructIO"